% Обчислення дисперсії передачі сигналу оптимальним фільтром
% L = 64
fs = 200;
N =  400;
t = (0:(N-1))/fs; 
v = 2*randn(size(t));  
s = sin(2*pi*10*t) + sin(2*pi*20*t);
x = s+v;
a = 1;
L = 64; % порядок фільтра
w = wiener_hopf(x, s, L);% обчислення коефіцієнтів
b = w;
y = filter(b,a,s);
Dispersiya64 = var(y) %обчислення дисперсії
 % L = 128
fs = 200;
N =  400;
t = (0:(N-1))/fs; 
v = 2*randn(size(t));  
s = sin(2*pi*10*t) + sin(2*pi*20*t);
x = s+v;
L = 128;    % порядок фільтра
w = wiener_hopf(x, s, L);% обчислення коефіцієнтів
b = w;
a = 1;
y = filter(b,a,s);
Dispersiya128 = var(y)   %обчислення дисперсії
 % L = 256
fs = 200;
N =  400;
t = (0:(N-1))/fs; 
v = 2*randn(size(t));  
s = sin(2*pi*10*t) + sin(2*pi*20*t);
x = s+v;
a = 1;
L = 256;    % порядок фільтра
w = wiener_hopf(x, s, L);% обчислення коефіцієнтів
b = w;
y = filter(b,a,s);
Dispersiya256 = var(y)   %обчислення дисперсії

